Finally figured it out! LaTeX tool can now convert to docx, which can be read in Pages! Also preserves figures!

diff --git a/bin/document b/bin/document
--- a/bin/document
+++ b/bin/document
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# May need bash 4
+#------------------------------------------------------------------------------#
+# May require bash 4.0
 # This script compile LaTeX documents on macOS
 # * Will compile a RTF version of document if filename is specially
 #   formatted like manuscriptYYYY-MM-DD.tex
@@ -11,26 +12,18 @@
 #   latexmk where would always end up with random extra files being created. Only
 #   way to consistently remove those temporary files was to query files present in
 #   folder before/after compiling step; delete the new ones. This is better!
+#------------------------------------------------------------------------------#
+# Initial stuff
 shopt -s nullglob # glob-expand into zero entries
 latex=pdflatex # by default use pdflatex
 bibtex=bibtex # for compiling bibliographies
 templates="$HOME/latex" # location of LaTeX templates and style files
 filename="$1" # the current file
 htmlcompile="$2" # option
-if [ -z "$filename" ]; then
-  echo "Error: Must call compile-script with filename."
-  exit 1
-fi
-if [ -z "$htmlcompile" ]; then
-  echo "Error: Must call compile-script with true/false compile option for HTML version."
-  exit 1
-fi
-if [ ! -r "$filename" ]; then
-  echo "Error: File \"$filename\" does not exist."
-  exit 1
-fi
-
-# Initial stuff
+[ $TERM_PROGRAM = "Apple_Terminal" ] && terminal="Terminal" || terminal="$TERM_PROGRAM"
+[ -z "$filename" ]    && echo "Error: Must call compile-script with filename."                                 && exit 1
+[ -z "$htmlcompile" ] && echo "Error: Must call compile-script with true/false option for converting to docx." && exit 1
+[ ! -r "$filename" ]  && echo "Error: File \"$filename\" does not exist."                                      && exit 1
 if [[ "$filename" =~ / ]]; then # i.e. contains directory specifier
   directory="${filename%/*}" # trim shortest pattern matching <stuff>/*, keep "stuff"
   filename="${filename##*/}" # trim longest pattern matching */<stuff>, keep "stuff"
@@ -39,6 +32,7 @@ if [[ "$filename" =~ / ]]; then # i.e. contains directory specifier
 fi
 filestem="${filename%.tex}" # simple
 
+#------------------------------------------------------------------------------#
 # Parse raw file to get some options
 # First if GIF/animation in file, need to change from Skim to compatible viewer
 cat "$filename" | grep -o '^[^%]*' | grep '\\animategraphics' &>/dev/null && viewer="Adobe Acrobat Reader DC" || viewer="Skim"
@@ -54,16 +48,29 @@ cat "$filename" | grep '\\documentclass\[.*\]{beamer}' &>/dev/null \
 cat "$filename" | grep -o '^[^%]*' | egrep 'fontspec|xltxtra' &>/dev/null \
   && latex=xelatex && dfilename="" && htmlcompile=false
 
-################################################################################
+#------------------------------------------------------------------------------#
 # Manage all LaTeX files, and move them around if necessary
-################################################################################
-# Helper function for removing stuff
-function remove() {
-  [ -r "$1" ] && [ "$(realpath "$(pwd)")" != "$(realpath $templates)" ] \
-    && rm "$1" # removes .sty or .bst file if not in template directory
+#------------------------------------------------------------------------------#
+# Functino to remove massive number of auxiliary files generated by
+# htlatex files and beamer files; extensions can be super weird so simply
+# removing a list of extensions won't cut it; instead just detect new files
+# Change ext_ignore to add exceptions to the deleted temporary files
+function cleanup() {
+  files_new=(*) # new files
+  files_rm=() # record deleted
+  ext_ignore=(tex bbl pdf docx png jpg jpeg eps gif)
+  for file_new in "${files_new[@]}"; do
+    if [[ ! " ${files_old[@]} " =~ " $file_new " ]]; then
+      if [[ ! " ${ext_ignore[@]} " =~ " ${file_new##*.} " ]]; then
+        echo "Removed file: $file_new."
+        rm "$file_new" # delete the file
+        files_rm+=("$file_new")
+      fi
+    fi
+  done
 }
 
-# Helper function for finding stuff
+# Function to find stuff
 # * Supply with a list of latex-ish file names, then the extension as last argument
 # * Important to call kpsewhich with a list of files rather than calling it
 #   successively; otherwise can be extremely slow, for some strange reason
@@ -72,12 +79,11 @@ function latexfind() {
   ext=${!#} # the last argument
   names=($(echo ${@:1:$#-1} | tr " " "\n" | sort)) # the previous arguments 
   files=($(kpsewhich ${names[@]/%/.${ext}})) # append suffix to each file
-  # echo NAMES "${names[@]/%/.${ext}}"
-  # echo FOUND ${files[@]##*/} # show the files found
   for name in ${names[@]}; do
     file="${name}.${ext}" # file we want
     # Potentially delete local file to 'refresh' things
-    # remove ${file}
+    # [ -r "$1" ] && [ "$(realpath "$(pwd)")" != "$(realpath $templates)" ] \
+    #   && rm "$1" # removes .sty or .bst file if not in template directory
     # Determine location and stuff
     if [[ ${files[@]} =~ $file ]]; then # search succeeded
       # if [ -e "./${file##*/}" ]; then
@@ -98,6 +104,7 @@ function latexfind() {
   done
 }
 
+#------------------------------------------------------------------------------#
 # Automatically detect custom .cls file and copy it over
 # Will ignore commented out lines; see https://unix.stackexchange.com/a/157607/112647
 # Also ignore documentclass calls within verbatim commands; or just enforce starts at 0 position
@@ -107,6 +114,7 @@ class=($(cat "$filename" | grep -o '^[^%]*' | grep '^\\documentclass' |
 echo "Finding class file..."
 latexfind $class cls
 
+#------------------------------------------------------------------------------#
 # As above but for the RequirePackage lines in the .cls file
 # * Have encountered a RequirePackage inside AtEndOfClass, so we also account for that
 # * Also must delete stuff inside [] to account for possible nested {} argument
@@ -146,35 +154,15 @@ elif [ ${#bibstyle[@]} -gt 1 ]; then
   echo "More than one bibliographystyle found." && exit 1
 fi
 
-################################################################################
+#------------------------------------------------------------------------------#
 # Compile the document and display it
-################################################################################
+#------------------------------------------------------------------------------#
 # Set the flags for compiling
 # * Nonstop mode means no interaction, but keep trying to compile if encounter errors.
 # * The shellescape option helps use eps figures that aren't in actual .tex directory.
 #   See: https://www.scivision.co/pdflatex-error-epstopdf-output-filename-not-allowed-in-restricted-mode/
 flags="-interaction=nonstopmode --shell-escape"
-
-# Helper function for deleting extra files
-# Call this before exiting every time
-oldfiles=(*) # glob expansion to every filename
-function cleanup() {
-  # Delete extra files
-  newfiles=(*) # new files
-  deletefiles=() # record deleted
-  ignorestems=(tex html rtf pdf bbl doc png jpg jpeg eps gif) # ignore these
-  for filenew in "${newfiles[@]}"; do
-    if [[ ! " ${oldfiles[@]} " =~ " $filenew " ]]; then
-      if [[ ! " ${ignorestems[@]} " =~ " ${filenew##*.} " ]]; then
-        echo "Removed file: $filenew."
-        rm "$filenew" # delete the file
-        deletefiles+=("$filenew")
-      fi
-    fi
-  done
-  # [ "${#deletefiles[@]}" -gt 0 ] && echo "Deleted files:"" ${deletefiles[@]}"
-}
-
+files_old=(*) # glob expansion to every filename
 # Compile normal PDF, or the track-changes version
 # * Always compile TWICE to enable glossary-references, equation-references
 # * If bibliography present, compile once to get .aux file, run bibtex
@@ -202,17 +190,17 @@ if [ ! -r "$filestem.pdf" ]; then
   exit 1
 fi
 
-# Get difference-LaTeX file, with track changes
+#------------------------------------------------------------------------------#
+# Create the difference-LaTeX file, with track changes
 if [ ! -z "$dfilename" ] && [[ ! "$dfilename" =~ meeting ]]; then
   echo "The filename contains a date string. Will run latexdiff on the previous version."
   # Check for earlier version
   prefix=${filename%[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].tex} # parameter expensions are fire yo
   pfiles=($prefix[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].tex) # sorted manuscript files (glob is sorted by default)
-  # echo PREFIX $prefix FILES ${pfiles[@]}
   for index in "${!pfiles[@]}"; do
+    # Get the part of list corresponding to files that
+    # come BEFORE current one in alphanumeric sorting
     [ "${pfiles[$index]}" == "$filename" ] && break
-      # get the part of list corresponding to files that
-      # come BEFORE current one in alphanumeric sorting
   done
   # Create difference file if earlier version exists
   if [ "$index" -eq 0 ]; then echo "Warning: Cannot find previous version of this file."
@@ -243,30 +231,44 @@ if [ ! -z "$dfilename" ] && [[ ! "$dfilename" =~ meeting ]]; then
   fi
 fi
 
-# Get HTML or RTF-LaTeX file
+#------------------------------------------------------------------------------#
+# Get docx file that is readable in Word and Pages
 if $htmlcompile; then
-# if [ ! -z "$rfilename" ] && $htmlcompile; then
-  # echo "HIHIHIHI"
-  echo "Creating HTML file with htlatex."
-  htlatex "$filename" | sed -E '/^! |^l\./!d' | sed $'s/^! /\\\n/g' | tail +2
-  if [ ! -r "$filestem.html" ]; then
-    echo "Error: Conversion to HTML failed." && cleanup
-    exit 1
+  if ! type htlatex &>/dev/null; then
+    echo "Warning: HTLaTeX not found."
+  elif ! type pandoc &>/dev/null; then
+    echo "Warning: Pandoc not found, please install it with Homebrew."
+  else
+    # First get HTML file
+    # Will filter most messages so more pallatable, only preserve errors and warnings
+    echo "Creating HTML file with htlatex."
+    htlatex "$filename" | sed -E '/^! |^l\./!d' | sed $'s/^! /\\\n/g' | tail +2
+    if [ ! -r "$filestem.html" ]; then
+      echo "Error: Conversion to HTML failed." && cleanup
+      exit 1
+    fi
+    # Next change encoding to utf-8; can do it with vim
+    # See: https://stackoverflow.com/a/23235290/4970632
+    # vim -c "set fileencoding=utf-8 | wq" "$filestem.html"
+    # Instead do it with iconv, which should come with most UNIX distros and conda
+    # See: https://tex.stackexchange.com/a/200182/73149
+    # Have to specify ASCII (the ISO string) manually for some reason, or it fails
+    iconv -f ISO-8859-1 -t UTF-8 "$filestem.html" > "tmp.html" && mv tmp.html "$filestem.html"
+    # Finally convert to docx with pandoc; this will keep figures!
+    # * Note that converting to a .doc extension will just leave the HTML, because
+    #   pure HTML technically is compatible with the .doc extensions specs.
+    # * If you browse the docx file with vim, will show message that we are browsing
+    #   a 'zipfile', and you can descend into different sections.
+    echo "Converting HTML to .docx with pandoc, so can be read in Word and Pages."
+    pandoc -s "$filestem.html" -o "$filestem.docx"
   fi
-  mv "$filestem.html" "$filestem.doc"
-  # echo "Creating RTF file with latex2rtf."
-  # latex2rtf "$filename" # | sed -E '/^! |^l\./!d' | sed $'s/^! /\\\n/g' | tail +2
-  # if [ ! -r "$filestem.rtf" ]; then
-  #   echo "Error: Conversion to RTF failed." && cleanup
-  #   exit 1
-  # fi
 fi
 
+#------------------------------------------------------------------------------#
 # Clean things up and open the appropriate apps
-cleanup # delete new files
+cleanup
 open -a "$viewer" "$filestem.pdf" # open new pdf
 [ ! -z "$dfilestem" ] && open -a "$viewer" "$dfilestem.pdf" # open difference
-[ -z $TERM_PROGRAM ] && echo "Error: Could not find terminal from which this command executed." && exit 1
-[ $TERM_PROGRAM = "Apple_Terminal" ] && terminal="Terminal" || terminal="$TERM_PROGRAM"
+[ -e "$filestem.docx" ] && open -a "pages" "$filestem.docx" # open document
 open -a $terminal # bring terminal back into focus
 
