Git aliases, minor changes

diff --git a/bin/git-delete b/bin/git-delete
--- a/bin/git-delete
+++ b/bin/git-delete
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# set -o errexit
 #------------------------------------------------------------------------------#
 # Author: David Underhill
-# Script to permanently delete files/folders from your git repository. To use
+# Script to permanently delete files/folders from your git history. To use
 # it, cd to your repository's root and then run the script with a list of paths
-# you want to delete, e.g., git-delete path1 path2, or with glob patterns
+# you want to delete, e.g., git-delete path1 path2, or with glob patterns.
+# Try also 'git deleted' and 'git objects' to see which files are bad.
 #------------------------------------------------------------------------------#
 # Original script:
 # set -o errexit
@@ -25,18 +25,11 @@
 # Purpose of tag-name-filter:
 # https://stackoverflow.com/q/21009947/4970632
 #------------------------------------------------------------------------------#
-# Checks
-if [ $# -ne 1 ]; then
-  echo "Error: Need exactly 1 argument (file or glob pattern)."
-  exit 1
-fi
-
 # Test if unstaged changes
+[ $# -ne 1 ] && echo "Usage: git delete FILE_OR_PATTERN" && exit 1
 root="$(git rev-parse --show-toplevel)"
 stat="$(git status --porcelain)"
-if [ -n "$stat" ]; then
-  echo "Error: Unstaged changes detected." && exit 1
-fi
+[ -n "$stat" ] && echo "Error: Unstaged changes detected." && exit 1
 
 # Preserve current ones (mv is super fast, so while this is ugly, no big deal)
 pattern="$@" # the glob pattern
diff --git a/bin/git-truncate b/bin/git-truncate
--- a/bin/git-truncate
+++ b/bin/git-truncate
@@ -1,22 +1,40 @@
 #!/bin/bash -e
+#------------------------------------------------------------------------------#
+# Rev parse method
+# Copied from: https://stackoverflow.com/a/34829535/4970632
+#------------------------------------------------------------------------------#
+# Shallow to last 5 commits
+[ $# -ne 1 ] && echo "Usage: git truncate NUM_COMMITS" >&2 && exit 1
+git rev-parse HEAD~$1 > .git/shallow
+# Prune unreachable objects
+git fsck --unreachable # Will show you the list of what will be deleted
+git gc --prune=now     # Will actually delete your data
+
+#------------------------------------------------------------------------------#
+# Clone method
+# Copied from: https://stackoverflow.com/a/34829535/4970632
+#------------------------------------------------------------------------------#
+# Clone the original repo into limitedRepo
+# git clone file:///path_to/originalRepo limitedRepo --depth=10
+# Remove the original repo, to free up some space
+# rm -rf originalRepo
+# cd limitedRepo
+# git remote rm origin
+
+#------------------------------------------------------------------------------#
+# Filter branch method
 # Copied from: https://gist.github.com/magnetikonline/5062718
 # Inspired by: https://github.com/adrienthebo/git-tools/blob/master/git-truncate
-if [[ (-z $1) || (-z $2) ]]; then
-  echo "Usage: $(basename "$0") DROP_AT_SHA1 BRANCH"
-  exit 1
-fi
-if [[ ! $1 =~ ^[0-9a-f]{7,40}$ ]]; then
-  echo "Error: Invalid Git commit SHA1" >&2
-  exit 1
-fi
-# Note: if fails - include [--force] argument
-git filter-branch \
-  --parent-filter "sed \"s/-p $1[0-9a-f]*//\"" \
-  --prune-empty \
-  -- "$2"
-IFS=$'\n'
-for ref_name in $(git for-each-ref --format="%(refname)" refs/original); do
-  echo "$ref_name"
-  git update-ref -d "$ref_name"
-done
-git gc --aggressive --prune=all
+#------------------------------------------------------------------------------#
+# [ $# -ne 2 ] && echo "Usage: $(basename "$0") DROP_AT_SHA1 BRANCH" >&2 && exit 1
+# ! [[ $1 =~ ^[0-9a-f]{7,40}$ ]] && echo "Error: Invalid Git commit SHA1" >&2 && exit 1
+# git filter-branch \
+#   --parent-filter "sed \"s/-p $1[0-9a-f]*//\"" \
+#   --prune-empty \
+#   -- "$2"
+# IFS=$'\n'
+# for ref_name in $(git for-each-ref --format="%(refname)" refs/original); do
+#   echo "$ref_name"
+#   git update-ref -d "$ref_name"
+# done
+# git gc --aggressive --prune=all
