Minor

diff --git a/bin/git-delete b/bin/git-delete
--- a/bin/git-delete
+++ b/bin/git-delete
@@ -21,4 +21,14 @@ git filter-branch -f --index-filter "git rm -rf --cached --ignore-unmatch -- $fi
 
 # Remove the temporary history git-filter-branch otherwise leaves behind for a long time
 # rm -rf .git/refs/original && rm -rf .git/logs/
-rm -rf "$folder/refs/original/" && git reflog expire --all && git gc --aggressive --prune
+echo "Deleting refs."
+rm -rf "$folder/refs/original/"
+[ $? -ne 0 ] && echo "Error" && exit 1
+
+echo "Deleting logs."
+git reflog expire --all
+[ $? -ne 0 ] && echo "Error" && exit 1
+
+echo "Running git gc."
+git gc --aggressive --prune
+[ $? -ne 0 ] && echo "Error" && exit 1
