Add git delete tool

diff --git a/bin/git-delete b/bin/git-delete
--- a/bin/git-delete
+++ b/bin/git-delete
@@ -7,36 +7,74 @@ set -o errexit
 # For *some improvements* see:
 # https://stackoverflow.com/a/5985276/4970632
 # which will prune empty commits.
+# Another resource:
+# https://blog.ostermiller.org/git-remove-from-history
 # See:
 # https://stackoverflow.com/a/18197405/4970632
 # https://development.robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/
 # which reference github file on: https://gist.githubusercontent.com/nottrobin/5758221/raw/ff740b4ac3b8ab80d40e3598ec461400dce42b5d/git-prune
-if [ $# -eq 0 ]; then
-  exit 0
+# When to use tag-name-filter:
+# https://stackoverflow.com/q/21009947/4970632
+if [ $# -ne 1 ]; then
+# if [ $# -le 1 ]; then
+  echo "Error: Need exactly 1 argument (file or glob pattern)."
+  exit 1
 fi
 
+# Test if unstaged changes
+root="$(git rev-parse --show-toplevel)"
+stat="$(git status --porcelain)"
+if [ -n "$stat" ]; then
+  echo "Error: Unstaged changes detected." && exit 1
+fi
+
+# Preserve current ones (mv is super fast, so while this is ugly, no big deal)
+# echo "Adding to gitignore: ${resurrect[@]}"
+pattern="$@" # the glob pattern
+echo "Adding to gitignore: $pattern"
+nlines=$(wc -l < "$root/.gitignore")
+printf "\n# Filter-branch files\n" >>"$root/.gitignore"
+git rm -r --cached "$pattern"
+echo "$pattern" >>"$root/.gitignore"
+git add --all && git commit -q -m "Remove matches."
+# current=($(git ls-files))
+# files=($@) # also expand glob pattern
+# for file in "${current[@]}"; do
+#   if [[ " ${files[@]} " =~ " $file " ]]; then
+#     resurrect+=("$file")
+#   else
+#     deleted+=("$file");
+#   fi
+# done
+# for file in "${resurrect[@]}"; do
+#   git rm -r --cached "$file"
+#   echo "$file" >>"$root/.gitignore"
+# done
+
 # Remove all paths passed as arguments from the history of the repo
-# Use -f because often 'backup already exists'
-files=$@
-folder="$(git rev-parse --show-toplevel)/.git"
-# git filter-branch -f --prune-empty --index-filter "git rm -rf --cached --ignore-unmatch -- $files" HEAD
-git filter-branch -f --prune-empty --tag-name-filter cat --index-filter "git rm -rf --cached --ignore-unmatch -- $files" HEAD
+# NOTE: Make sure to remove from *all* branches using -- --all instead of HEAD
+echo "Filtering branch."
+git filter-branch -f --prune-empty --index-filter "git rm -rf --cached --ignore-unmatch -- $pattern" -- --all
 
 # Remove the temporary history git-filter-branch otherwise leaves behind for a long time
+echo "Deleting refs and logs."
+rm -rf "$root/.git/refs/original/"
+git reflog expire --verbose --expire=now --all
+# git reflog expire --all
 # rm -rf .git/refs/original && rm -rf .git/logs/
-echo "Deleting refs."
-rm -rf "$folder/refs/original/"
-[ $? -ne 0 ] && echo "Error" && exit 1
-
 # Not sure what this does, from that first link (not original script)
 # git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
 
-echo "Deleting logs."
-git reflog expire --verbose --expire=0 --all
-# git reflog expire --all
+echo "Running git gc."
+git gc --aggressive --prune=now
 [ $? -ne 0 ] && echo "Error" && exit 1
 
-echo "Running git gc."
-# git gc --aggressive --prune
-git gc --aggressive --prune=0
-[ $? -ne 0 ] && echo "Error" && exit 1
+# Move matches back
+echo "Fixing gitignore"
+hash gsed 2>/dev/null && sub=gsed || sub=sed
+$sub -i "$(($nlines+1)),\$d" "$root/.gitignore"
+# sed -i -n "/$prefix/q;p" "$root/.gitignore"
+# echo "Moving deleted files back."
+# for file in "${files[@]}"; do
+#   mv "$tmp/$file" "$root/$file"
+# done
