Various improvements.

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -8,8 +8,13 @@
 #   the function will fail.
 shopt -s nullglob # glob-expand into zero entries
 filename="$1" # the current file
+htmlcompile="$2" # option
 if [ -z "$filename" ]; then
   echo "ERROR: Must call compile-script with filename."
+  exit 1
+fi
+if [ -z "$htmlcompile" ]; then
+  echo "ERROR: Must call compile-script with true/false compile option for HTML version."
   exit 1
 fi
 if [ ! -r "$filename" ]; then
@@ -24,7 +29,7 @@ function cleanup() {
   # Delete extra files
   newfiles=(*) # new files
   deletefiles=() # record deleted
-  ignorestems=(tex html rtf pdf bbl) # ignore these
+  ignorestems=(tex html rtf pdf bbl doc) # ignore these
   for filenew in "${newfiles[@]}"; do
     if [[ ! " ${oldfiles[@]} " =~ " $filenew " ]]; then
       if [[ ! " ${ignorestems[@]} " =~ " ${filenew##*.} " ]]; then
@@ -75,7 +80,8 @@ bibfiles=(*.bib) # glob expansion of bibTeX files; for now don't expect "standar
 if [ ${#bibfiles[@]} -gt 1 ]; then
   echo "ERROR: Ambiguous which bibliography we should choose. Found the following: ${bibfiles[@]}."
   exit 1
-elif [ ${#bibfiles[@]} -eq 1 ] && [ $string != "supplementary" ]; then
+# elif [ ${#bibfiles[@]} -eq 1 ] && [ $string != "supplementary" ]; then
+elif [ ${#bibfiles[@]} -eq 1 ]; then
   bibfile="${bibfiles[0]}" # choose this one
 fi
 
@@ -102,8 +108,7 @@ if [ ! -r "$filestem.pdf" ]; then
 fi
 
 # Get difference-LaTeX file, with track changes
-if [ ! -z "$dfilename" ] && true; then
-  echo "yi"
+if [ ! -z "$dfilename" ] && false; then
   [ -r "$dfilename" ] && rm "$dfilename" # otherwise shows up in list
   # texfiles=(*.tex) # delete old difference
   texfiles=($string????-??-??.tex) # sorted manuscript files (glob is sorted by default)
@@ -128,7 +133,7 @@ if [ ! -z "$dfilename" ] && true; then
 fi # end check whether file-format implies we want difference
 
 # Get HTML or RTF-LaTeX file
-if [ ! -z "$rfilename" ]; then
+if [ ! -z "$rfilename" ] && $htmlcompile; then
   echo "Creating HTML file with htlatex."
   htlatex "$filename" | sed -E '/^! |^l\./!d' | sed $'s/^! /\\\n/g' | tail +2
   if [ ! -r "$filestem.html" ]; then
@@ -136,6 +141,7 @@ if [ ! -z "$rfilename" ]; then
     cleanup
     exit 1
   fi
+  mv "$filestem.html" "$filestem.doc"
   # echo "Creating RTF file with htlatex."
   # latex2rtf "$filename"
   # # | sed -E '/^! |^l\./!d' | sed $'s/^! /\\\n/g' | tail +2
