Various improvements and additional features. Organized latex templates. New figuresync command for syncing updated figures in remote project directory to local directory. Fixed compile function.

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -7,7 +7,9 @@
 #   for every version of the manuscript. If you have more than one .bib file
 #   the function will fail.
 shopt -s nullglob # glob-expand into zero entries
-templates="$HOME/templates" # location of LaTeX templates and style files
+latex=pdflatex # by default use pdflatex
+bibtex=bibtex # for compiling bibliographies
+templates="$HOME/latex" # location of LaTeX templates and style files
 filename="$1" # the current file
 htmlcompile="$2" # option
 if [ -z "$filename" ]; then
@@ -22,6 +24,12 @@ if [ ! -r "$filename" ]; then
   echo "ERROR: File \"$filename\" does not exist."
   exit 1
 fi
+
+# Helper function
+function remove() {
+  [ -r "$1" ] && [ "$(realpath "$(pwd)")" != "$(realpath $templates)" ] \
+    && rm "$1" # removes .sty or .bst file if not in template directory
+}
 
 # Initial stuff
 if [[ "$filename" =~ / ]]; then # i.e. contains directory specifier
@@ -39,22 +47,59 @@ cat "$filename" | grep -v '^ *%' | grep '\\animategraphics' &>/dev/null && viewe
 cat "$filename" | grep -v '^ *%' | egrep '\\bibliography{.*}|\\printbibliography' &>/dev/null && bibliography=true || bibliography=false
 # Finally detect if we want to run latexdiff on this file
 [[ "$filename" =~ .*[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].tex ]] && dfilename="${filename%.tex}changes.tex" || dfilename="" # keep empty
-# And detect if beamer presentation
-cat "$filename" | grep '\\documentclass\[.*\]{beamer}' &>/dev/null && beamer=true || beamer=false
-$beamer && echo "Beamer presentation detected." && dfilename="" # never want difference files on beamer presentations, duh
+# Change compile options
+cat "$filename" | grep '\\documentclass\[.*\]{beamer}' &>/dev/null \
+  && latex=latex && dfilename="" && htmlcompile=false # beamer options
+# cat "$filename" | grep '\\usepackage{.*fontspec.*}' &>/dev/null \
+cat "$filename" | grep 'fontspec' &>/dev/null \
+  && latex=xelatex && dfilename="" && htmlcompile=false
 
 # Automatically copy over custom .sty files
 # Will ignore commented out lines; see https://unix.stackexchange.com/a/157607/112647
-packages=($(cat "$filename" | grep -o '^[^%]*' | \
-  grep '^.*\\usepackage' | cut -d'{' -f2 | cut -d'}' -f1))
+# Will also detect \usepackage{package1,package2} lists
+packages=($(cat "$filename" | grep -o '^[^%]*' |  grep '^.*\\usepackage' \
+  | cut -d'{' -f2 | cut -d'}' -f1 | tr ',' ' ' | xargs))
+# for f in *.sty; do echo $f; done
 for package in ${packages[@]}; do
-  # echo "Searching for ${package}.sty."
+  # Potentially delete local .sty file to 'refresh' things
+  # May comment this out in future
+  # remove "./${package}.sty"
+  # Find packages and potentially copy from custom directory
   if ! kpsewhich ${package}.sty &>/dev/null; then # search failed
+    if [ -r "${templates}/${package}.sty" ]; then
+      echo "Copying \"${package}.sty\" from latex directory to current directory."
+      cp "${templates}/${package}.sty" ./
+    else
+      echo "Package \"${package}.sty\" not found in latex directory or with kpsewhich."
+      exit 1
+    fi
+  elif [ -r "./${package}.sty" ]; then
+    echo "Using \"${package}.sty\" from current directory."
   else
-    echo "Package ${package}.sty not found in templates folder."
+    echo "Using \"${package}.sty\" from TeXLive distribution."
   fi
 done
-exit
+
+# As above but for .bst file
+bibstyle=($(cat "$filename" | grep -o '^[^%]*' | \
+  grep '^.*\\bibliographystyle' | cut -d'{' -f2 | cut -d'}' -f1))
+if [ ! -z $bibstyle ]; then
+  [ ${#bibstyle[@]} -gt 1 ] && echo "More than one bibliographystyle found." && exit 1
+  remove "./${bibstyle}.bst"
+  if ! kpsewhich ${bibstyle}.bst &>/dev/null; then # search failed
+    if [ -r "${templates}/${bibstyle}.bst" ]; then
+      echo "Copying \"${bibstyle}.bst\" from latex directory to current directory."
+      cp "${templates}/${bibstyle}.bst" ./
+    else
+      echo "Bibliography style \"${bibstyle}.bst\" not found in latex directory or with kpsewhich."
+      exit 1
+    fi
+  elif [ -r "./${bibstyle}.bst" ]; then
+    echo "Using \"${bibstyle}.bst\" from current directory."
+  else
+    echo "Using \"${bibstyle}.bst\" from TeXLive distribution."
+  fi
+fi
 
 # Set the flags for compiling
 # * Nonstop mode means no interaction, but keep trying to compile if encounter errors.
@@ -89,9 +134,7 @@ function cleanup() {
 #   bibtex <file>.aux), then run TWICE as before.
 # * See this page for matching consecutive lines with SED:
 #   https://unix.stackexchange.com/q/165362/112647
-$beamer && latex=xelatex || latex=pdflatex # some fancy .sty beamer packages need xelatex
-latex=pdflatex
-bibtex=bibtex
+echo "Compiling with $latex."
 if $bibliography; then
   echo "Preparing bibliography..."
   $latex -draftmode $flags "$filestem" &>/dev/null
